name: 鸣潮签到

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches:
  #    - master
  schedule:
    - cron: "0 16 * * *"
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run script
      env:
        COOKIE: ${{ secrets.COOKIE }}
        devCode: ${{ secrets.devCode }}
      run: python mcMain.py
